### ISSUE TITLE
Build error on node 12

### ISSUE THREAD

**Issue by ZackMattor** [lwille/node-gphoto2#128]
I can provide more details later - on a time crunch at the moment. But just for people trying to use the lib and getting build errors while installing the package wit NPM - just roll back to using node 11 for now.

Will try to capture logs for debugging later.

**Comment by jtleniger** [comment]
@ZackMattor is it the same error as #129 ?

**Comment by pawelrupek** [comment]
I experienced the same issue with Node 13 and believe that this error is indeed related to #129. I can provide a pull request which works with Nodejs v13 (all tests are passing on Linux with a Canon EOS 700D), but I do not have time to test backward compatibility. 

Caveats: 
* I did not fix the compiler warnings
* I have no experience with V8 or Nan

```
$ node --version
v13.12.0

$ node-gyp --version
v6.1.0

$ npm --version
6.14.4

$ uname -a
Linux test 5.4.30-1-MANJARO #1 SMP PREEMPT Thu Apr 2 17:31:45 UTC 2020 x86_64 GNU/Linux

$ clang --version
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ pkg-config --modversion libgphoto2
2.5.24
```

Here's the build output before fixing the code:

```
In file included from ../src/././binding.h:12,
                 from ../src/./camera.h:10,
                 from ../src/camera.cc:8:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/camera.cc: In static member function ‘static void GPCamera::Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/camera.cc:43:38: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   43 |   constructor.Reset(tpl->GetFunction());
      |                                      ^
In file included from ../src/././binding.h:11,
                 from ../src/./camera.h:10,
                 from ../src/camera.cc:8:
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:6283:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6283 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:6283:46: note:   candidate expects 1 argument, 0 provided
../src/camera.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE GPCamera::DownloadPicture(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/camera.cc:173:85: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
  173 |   v8::Local<v8::Value> source = options->Get(Nan::New("cameraPath").ToLocalChecked());
      |                                                                                     ^
In file included from ../src/././binding.h:11,
                 from ../src/./camera.h:10,
                 from ../src/camera.cc:8:
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
 3594 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3594:43: note:   candidate expects 2 arguments, 1 provided
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
 3597 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3597:43: note:   candidate expects 2 arguments, 1 provided
../src/camera.cc:174:85: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
  174 |   v8::Local<v8::Value> target = options->Get(Nan::New("targetPath").ToLocalChecked());
      |                                                                                     ^
In file included from ../src/././binding.h:11,
                 from ../src/./camera.h:10,
                 from ../src/camera.cc:8:
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3594:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
 3594 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3594:43: note:   candidate expects 2 arguments, 1 provided
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3597:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
 3597 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3597:43: note:   candidate expects 2 arguments, 1 provided
../src/camera.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE GPCamera::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/camera.cc:360:105: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>)’
  360 |   info.This()->Set(Nan::New("model").ToLocalChecked(), Nan::New(camera->model_.c_str()).ToLocalChecked());
      |                                                                                                         ^
In file included from ../src/././binding.h:11,
                 from ../src/./camera.h:10,
                 from ../src/camera.cc:8:
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/camera.cc:361:103: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>)’
  361 |   info.This()->Set(Nan::New("port").ToLocalChecked(), Nan::New(camera->port_.c_str()).ToLocalChecked());
      |                                                                                                       ^
In file included from ../src/././binding.h:11,
                 from ../src/./camera.h:10,
                 from ../src/camera.cc:8:
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/test/.cache/node-gyp/13.12.0/include/node/node_object_wrap.h:85:78:   required from here
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10400 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/home/test/.cache/node-gyp/13.12.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [gphoto2.target.mk:113: Release/obj.target/gphoto2/src/camera.o] Error 1

```

**Comment by philipptrenz** [comment]
I'm trying to build `node-gphoto2` against Node v12, also having some issue:

```
error /Users/philipp/git/photo-booth-new/node_modules/gphoto2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/philipp/git/photo-booth-new/node_modules/gphoto2
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.1.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/philipp/git/photo-booth-new/node_modules/gphoto2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/philipp/.node-gyp/12.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/philipp/.node-gyp/12.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/philipp/.node-gyp/12.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/philipp/git/photo-booth-new/node_modules/gphoto2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/gphoto2/src/autodetect.o
  CXX(target) Release/obj.target/gphoto2/src/binding.o
  CXX(target) Release/obj.target/gphoto2/src/camera.o
../src/camera.cc:43:38: error: too few arguments to function call, single argument 'context' was not specified
  constructor.Reset(tpl->GetFunction());
                    ~~~~~~~~~~~~~~~~ ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8.h:5947:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/camera.cc:173:42: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  v8::Local<v8::Value> source = options->Get(Nan::New("cameraPath").ToLocalChecked());
                                         ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/camera.cc:174:42: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  v8::Local<v8::Value> target = options->Get(Nan::New("targetPath").ToLocalChecked());
                                         ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/camera.cc:360:16: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  info.This()->Set(Nan::New("model").ToLocalChecked(), Nan::New(camera->model_.c_str()).ToLocalChecked());
               ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/camera.cc:361:16: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  info.This()->Set(Nan::New("port").ToLocalChecked(), Nan::New(camera->port_.c_str()).ToLocalChecked());
               ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/philipp/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/gphoto2/src/camera.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/philipp/git/photo-booth-new/node_modules/gphoto2
``` 

The issue seems to be `GetFunction()`, which needs `context` as argument.
