### ISSUE TITLE
Test failures on Ubuntu 13.04 x64 / D700

### ISSUE THREAD

**Issue by michaelkoetter** [lwille/node-gphoto2#36]
Same versions of node.js and GPhoto as in #35, but running on Ubuntu 13.04 x64.
At least it doesn't segfault ;)

```
> gphoto2@0.1.2 test /home/michael/node-gphoto2
> node_modules/mocha/bin/mocha

1..9
ok 1 node-gphoto2 should find attached cameras
ok 2 node-gphoto2 should provide a list of settings
not ok 3 node-gphoto2 should allow saving camera settings
  Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/michael/node-gphoto2/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
ok 4 node-gphoto2 should return a proper error code when something goes wrong
not ok 5 node-gphoto2 should be able to take a picture without downloading
  Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/michael/node-gphoto2/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
not ok 6 node-gphoto2 should be able to take a picture and download it to a buffer
  Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/michael/node-gphoto2/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
not ok 7 node-gphoto2 should be able to take a picture and download it to the file system
  Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/michael/node-gphoto2/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
ok 8 node-gphoto2 should be able to take a picture and download it later
not ok 9 node-gphoto2 should be able to take a preview picture and send it over a socket
  Error: timeout of 25000ms exceeded
      at null.<anonymous> (/home/michael/node-gphoto2/node_modules/mocha/lib/runnable.js:140:21)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
# tests 9
# pass 4
# fail 5
/home/michael/node-gphoto2/node_modules/should/lib/should.js:2561: Uncaught AssertionError: expected '0' to equal 'ffd8'
/home/michael/node-gphoto2/node_modules/should/lib/should.js:1199: Uncaught AssertionError: expected -1 to not exist
```

**Comment by lwille** [comment]
Closed for lack of further information.
