### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by DiSanzes** [lwille/node-gphoto2#77]
Hello,

I'm just trying to let node-gphoto2 run on my Intel Edison, but it's keeping to fail the test.

I get this Error:

/home/root/gphoto2-2.5.8/gphoto2/gphoto2:1
(function (exports, require, module, __filename, __dirname) {ELF
                                                              ^
SyntaxError: Unexpected token ILLEGAL
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/root/node-gphoto2/test/camera.test.coffee:1:15)
  at Object.<anonymous> (/home/root/node-gphoto2/test/camera.test.coffee:1:1)
  at Module._compile (module.js:456:26)

I have the following versions: 
gphoto2         2.5.8          gcc, popt(m), no exif, no cdk, no aa, no jpeg, readline
libgphoto2      2.5.8          all camlibs, gcc, ltdl, no EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking

node  v0.10.38

Can you help me?

**Comment by Sija** [comment]
Closing due to the age of this issue, reopen if needed.
