### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by nickpolet** [lwille/node-gphoto2#79]
I am trying to use gphoto2 within a small electron application. I have installed all the dependencies and then gphoto2. NPM installs everything fine and the build process seems to work just fine.

When I try and require the gphoto2 lib, with 

```
 var gphoto2 = require('gphoto2');
```

I get the following error when trying to run the electron app.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at new require (module.js:384:17)
    at Object.<anonymous> (/home/npolet/dev/meteor/spinee-capture/main.js:13:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

I have tried "npm rebuild" and completely removing the node_modules folder and starting from scratch, yet i still get this error.

Using node 0.10.25 and electron-prebuilt 0.33.7

Any tips on getting this going?

**Comment by Sija** [comment]
Closing due to issue old age, for updates see #94.
